// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: diagnostics_api.proto

package base

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DiagnosticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpLink         *SignalId `protobuf:"bytes,1,opt,name=upLink,proto3" json:"upLink,omitempty"`
	DownLink       *SignalId `protobuf:"bytes,2,opt,name=downLink,proto3" json:"downLink,omitempty"`
	ServiceId      []byte    `protobuf:"bytes,3,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	DataIdentifier []byte    `protobuf:"bytes,4,opt,name=dataIdentifier,proto3" json:"dataIdentifier,omitempty"`
}

func (x *DiagnosticsRequest) Reset() {
	*x = DiagnosticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnostics_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsRequest) ProtoMessage() {}

func (x *DiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*DiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_diagnostics_api_proto_rawDescGZIP(), []int{0}
}

func (x *DiagnosticsRequest) GetUpLink() *SignalId {
	if x != nil {
		return x.UpLink
	}
	return nil
}

func (x *DiagnosticsRequest) GetDownLink() *SignalId {
	if x != nil {
		return x.DownLink
	}
	return nil
}

func (x *DiagnosticsRequest) GetServiceId() []byte {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

func (x *DiagnosticsRequest) GetDataIdentifier() []byte {
	if x != nil {
		return x.DataIdentifier
	}
	return nil
}

type DiagnosticsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw []byte `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *DiagnosticsResponse) Reset() {
	*x = DiagnosticsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diagnostics_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsResponse) ProtoMessage() {}

func (x *DiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diagnostics_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*DiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_diagnostics_api_proto_rawDescGZIP(), []int{1}
}

func (x *DiagnosticsResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

var File_diagnostics_api_proto protoreflect.FileDescriptor

var file_diagnostics_api_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x12,
	0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x75, 0x70, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x49, 0x64, 0x52, 0x06, 0x75, 0x70, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x2a, 0x0a, 0x08, 0x64, 0x6f,
	0x77, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x52, 0x08, 0x64, 0x6f,
	0x77, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x64, 0x61,
	0x74, 0x61, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x13,
	0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x72, 0x61, 0x77, 0x32, 0x63, 0x0a, 0x12, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x14, 0x53,
	0x65, 0x6e, 0x64, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x18, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_diagnostics_api_proto_rawDescOnce sync.Once
	file_diagnostics_api_proto_rawDescData = file_diagnostics_api_proto_rawDesc
)

func file_diagnostics_api_proto_rawDescGZIP() []byte {
	file_diagnostics_api_proto_rawDescOnce.Do(func() {
		file_diagnostics_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_diagnostics_api_proto_rawDescData)
	})
	return file_diagnostics_api_proto_rawDescData
}

var file_diagnostics_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_diagnostics_api_proto_goTypes = []interface{}{
	(*DiagnosticsRequest)(nil),  // 0: base.DiagnosticsRequest
	(*DiagnosticsResponse)(nil), // 1: base.DiagnosticsResponse
	(*SignalId)(nil),            // 2: base.SignalId
}
var file_diagnostics_api_proto_depIdxs = []int32{
	2, // 0: base.DiagnosticsRequest.upLink:type_name -> base.SignalId
	2, // 1: base.DiagnosticsRequest.downLink:type_name -> base.SignalId
	0, // 2: base.DiagnosticsService.SendDiagnosticsQuery:input_type -> base.DiagnosticsRequest
	1, // 3: base.DiagnosticsService.SendDiagnosticsQuery:output_type -> base.DiagnosticsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_diagnostics_api_proto_init() }
func file_diagnostics_api_proto_init() {
	if File_diagnostics_api_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_diagnostics_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiagnosticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diagnostics_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiagnosticsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_diagnostics_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diagnostics_api_proto_goTypes,
		DependencyIndexes: file_diagnostics_api_proto_depIdxs,
		MessageInfos:      file_diagnostics_api_proto_msgTypes,
	}.Build()
	File_diagnostics_api_proto = out.File
	file_diagnostics_api_proto_rawDesc = nil
	file_diagnostics_api_proto_goTypes = nil
	file_diagnostics_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DiagnosticsServiceClient is the client API for DiagnosticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiagnosticsServiceClient interface {
	SendDiagnosticsQuery(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error)
}

type diagnosticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagnosticsServiceClient(cc grpc.ClientConnInterface) DiagnosticsServiceClient {
	return &diagnosticsServiceClient{cc}
}

func (c *diagnosticsServiceClient) SendDiagnosticsQuery(ctx context.Context, in *DiagnosticsRequest, opts ...grpc.CallOption) (*DiagnosticsResponse, error) {
	out := new(DiagnosticsResponse)
	err := c.cc.Invoke(ctx, "/base.DiagnosticsService/SendDiagnosticsQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosticsServiceServer is the server API for DiagnosticsService service.
type DiagnosticsServiceServer interface {
	SendDiagnosticsQuery(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error)
}

// UnimplementedDiagnosticsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiagnosticsServiceServer struct {
}

func (*UnimplementedDiagnosticsServiceServer) SendDiagnosticsQuery(context.Context, *DiagnosticsRequest) (*DiagnosticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDiagnosticsQuery not implemented")
}

func RegisterDiagnosticsServiceServer(s *grpc.Server, srv DiagnosticsServiceServer) {
	s.RegisterService(&_DiagnosticsService_serviceDesc, srv)
}

func _DiagnosticsService_SendDiagnosticsQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticsServiceServer).SendDiagnosticsQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.DiagnosticsService/SendDiagnosticsQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticsServiceServer).SendDiagnosticsQuery(ctx, req.(*DiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiagnosticsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "base.DiagnosticsService",
	HandlerType: (*DiagnosticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDiagnosticsQuery",
			Handler:    _DiagnosticsService_SendDiagnosticsQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "diagnostics_api.proto",
}
